// ============================================================
// chargen-data.js
// Data extracted from the Block, Dodge, Parry BR source pages.
// These files are read-only; this file is the single source of
// truth for the character generator.
// ============================================================

// ── Attribute descriptors ────────────────────────────────────
const ATTRIBUTE_DESCRIPTORS = {
  FOR: { low: "Frágil (FOR ≤ 6)", high: "Robusto (FOR ≥ 15)" },
  DEX: { low: "Desajeitado (DEX ≤ 6)", high: "Ágil (DEX ≥ 15)" },
  VON: { low: "Indisciplinado (VON ≤ 6)", high: "Resoluto (VON ≥ 15)" },
};

// ── Age table ────────────────────────────────────────────────
// rolls: which d6 results map to this row
// skillsFormula: "fixed" | "d4" | "min2d4" | "max2d4"
const AGE_TABLE = [
  {
    rolls: [1],
    name: "Jovem",
    ageBase: 17,
    ageDice: 6,
    experience: "Inexperiente",
    forMod: -1, dexMod: 2, vonMod: -2,
    skillsFormula: "fixed", skillsFixed: 1,
  },
  {
    rolls: [2],
    name: "Emergente",
    ageBase: 23,
    ageDice: 10,
    experience: "Aprendendo",
    forMod: 0, dexMod: 1, vonMod: -1,
    skillsFormula: "min2d4",
  },
  {
    rolls: [3, 4],
    name: "Plena",
    ageBase: 33,
    ageDice: 10,
    experience: "No auge",
    forMod: 1, dexMod: 0, vonMod: 0,
    skillsFormula: "d4",
  },
  {
    rolls: [5],
    name: "Experiente",
    ageBase: 43,
    ageDice: 10,
    experience: "Experiente",
    forMod: 0, dexMod: -1, vonMod: 1,
    skillsFormula: "max2d4",
  },
  {
    rolls: [6],
    name: "Velha",
    ageBase: 53,
    ageDice: 10,
    experience: "Veterana",
    forMod: -1, dexMod: -2, vonMod: 2,
    skillsFormula: "fixed", skillsFixed: 4,
  },
];

// ── Fantastic Species ─────────────────────────────────────────
const SPECIES_TRAITS = [
  {
    name: "Robusto",
    examples: "anões, orcs etc.",
    description:
      "Uma vez ao dia, quando reduzido a Guarda 0, pode escolher ficar com Guarda 1 em vez disso.",
  },
  {
    name: "Arcano",
    examples: "elfos, demônios etc.",
    description:
      "Uma vez ao dia, pode tentar realizar um pequeno feito mágico relacionado à sua ancestralidade. O Mestre decide se algum Teste de Atributo é necessário.",
  },
  {
    name: "Astuto",
    examples: "halflings, goblins etc.",
    description: "Uma vez ao dia, pode rerolar qualquer Teste de Resistência.",
  },
  {
    name: "Adaptável",
    examples: "humanos, meio-humanos etc.",
    description:
      "Uma vez ao dia, pode usar um Atributo diferente para um Teste de Resistência, em vez do pedido pelo Mestre.",
  },
];

// ── Skills master list ────────────────────────────────────────
// Keyed by the name used in career lists. Descriptions from the
// skills reference tables. Variants/aliases map to the same entry.
const SKILL_DESCRIPTIONS = {
  // Aliados & Moral
  "Afinidade com Animais": "+1 em rolagens de reação com animais e bestas.",
  "Cantor": "Você sabe cantar canções estimulantes, inspirando aqueles ao seu redor.",
  "Comandante": "Uma vez por combate, emita um comando único a um aliado para melhorar seu próximo ataque ou para recuperar 1d6 Guarda.",
  "Companheiro": "Você tem um assistente, guarda-costas ou mensageiro (3d6 atributos, Guarda 3).",
  "Companheiro Animal": "Você tem um animal de estimação fiel (2d6 atributos, Guarda 3, d6 de ataque).",
  "Habilidades Impressionantes": "Após derrota impressionante de inimigo forte, peça aos espectadores Rolagens de Reação com +2 ou Rolagens de Moral com -2.",
  "Inspirador": "Aliados automaticamente passam nos testes de moral.",
  "Mediador": "+1 em rolagens de reação para aqueles com quem você compartilha uma língua.",
  "Palavras Estimulantes": "Uma vez por dia, incite aliados a causar mais dano: eles rolam dados de dano em dobro e escolhem o maior resultado ao atacar.",
  "Palavras Incitantes": "Uma vez por dia, incite aliados a causar mais dano: eles rolam dados de dano em dobro e escolhem o maior resultado ao atacar.",
  "Provocador": "Você pode forçar aqueles que te entendem a fazer um teste de VON. Se falharem, são compelidos a duelar com você.",

  // Combate
  "Alerta": "Você raramente é surpreendido. Diminui as chances do grupo ser pego de surpresa e sempre vence Testes de DEX de iniciativa no primeiro turno.",
  "Aparar da Cobra": "Ao realizar uma Parada e rolar um dano igual ao do seu oponente, você vence a parada.",
  "Defesa Ágil": "Estar desarmado lhe dá 1 de Armadura.",
  "Difícil de Matar": "Uma vez por dia, refaça seu Teste de Resistência para Dano Crítico em caso de falha.",
  "Disparo Crítico": "Em ataque à distância com dano superior à metade do dado, o próximo ataque do inimigo fica enfraquecido e ele fica incapaz de se mover.",
  "Disparo Incapacitante": "Você sabe atingir pontos vitais com ataques à distância, imobilizando o alvo.",
  "Empunhadura Firme": "Você nunca pode ser desarmado enquanto estiver consciente.",
  "Especialista em Armaduras": "Qualquer armadura que você use perde a etiqueta de \"Volumoso\".",
  "Fúria": "Em combate, você pode entrar em estado de fúria: qualquer dano causado ou recebido é aprimorado. Acalmar-se exige um Teste de VON (uma vez por turno).",
  "Golpe Paciente": "Se um Teste de DEX fosse feito para ver quem vai primeiro, você pode escolher falhar. Seu ataque será então aprimorado.",
  "Golpes Brutais": "Quando você causar 10 ou mais de dano em um único ataque, os ataques do alvo ficam enfraquecidos no próximo turno.",
  "Golpes Certos": "Por 1d4 de dano em VON por ataque, realize ataques desarmados que causam 1d8, ignoram Armadura e podem atingir fantasmas.",
  "Golpes Selvagens": "Faça um ataque aprimorado a custo de 1 de Fadiga.",
  "Guerreiro Montado": "Quando estiver montado, ataques contra alvos desarmados são aprimorados.",
  "Implacável": "Quando você causa Dano Crítico, isso imediatamente aciona um teste de Moral para os inimigos.",
  "Ira do Vento": "Após realizar uma Esquiva, seu próximo ataque contra o oponente atacante é aprimorado (se atacar na primeira oportunidade).",
  "Lutador de Arena": "Você tem +1 de armadura e FOR 18 se estiver em frente a um grande público.",
  "Mestre Arremessador": "Ao arremessar armas Rápidas ou Balanceadas, role dois dados de dano e escolha o maior. Com 1 em qualquer dado, a arma é quebrada ou perdida.",
  "Postura Defensiva": "Ganha +1 de Armadura ao empregar armas rápidas ou balanceadas defensivamente, sem escudo ou arma na outra mão.",
  "Proficiência com Armas Cortantes": "Você tem proficiência com armas cortantes e pode usar seus efeitos de tipo.",
  "Proficiência com Armas Contundentes": "Você tem proficiência com armas contundentes e pode usar seus efeitos de tipo.",
  "Proficiência com Armas Perfurantes": "Você tem proficiência com armas perfurantes e pode usar seus efeitos de tipo.",
  "Proteger": "Se aliados estiverem no mesmo combate corpo a corpo, pode abrir mão da sua ação para atrair todos os ataques para si.",
  "Pugilista": "Seus ataques desarmados causam dano de d6.",
  "Rápido": "Em situações de iniciativa, você age mais rapidamente do que o normal.",
  "Saque Rápido": "Com a arma específica para a qual treinou, você automaticamente vence Testes de DEX de iniciativa.",
  "Sede de Sangue": "Matar ou causar Dano Crítico a um inimigo recupera 1d3 Guarda.",
  "Soldado": "+1 de dano quando superar um inimigo em número no combate corpo a corpo.",
  "Trespassar": "Quando você mata ou causa Dano Crítico em um inimigo, pode atacar novamente.",
  "Visão de Túnel": "Uma vez por dia, escolha um oponente humanóide: seus ataques contra ele são aprimorados e os ataques dele contra você são enfraquecidos (outras fontes de dano contra você ficam aprimoradas).",

  // Esotérico & Arcano
  "Devoção": "Você ganha +1 Dado de Fé, até um total de 4.",
  "Dotado": "Você ganha +1 Dado de Magia, até um máximo de 4.",
  "Elemental": "Escolha um elemento (ex: Fogo, Gelo). Você sempre tem 3 de Armadura contra dano mágico desse elemento.",
  "Cura Pelas Mãos": "Uma vez por dia, cura alguém de uma doença ou veneno, ou restaura 1d6 de Força.",
  "Nariz Sensível": "Você pode cheirar criaturas Mortas-Vivas ou Maldosas nas proximidades.",
  "Olfato Sensível": "Você pode cheirar criaturas Mortas-Vivas ou Maldosas nas proximidades.",
  "Palavras de Graça": "Cure 1d6 de qualquer atributo, mas fique Desprovido até descansar.",
  "Sensibilidade Mágica": "Você pode perceber quando energias arcanas estão em ação e onde.",
  "Sentido Mágico": "Você pode perceber quando energias arcanas estão em ação e onde.",
  "Sentidos Aguçados": "Você sente uma \"sensação estranha\" quando há uma passagem secreta perto de você.",
  "Terceiro Olho": "Você não pode ser enganado por ilusões mágicas.",
  "Visão Noturna": "Seus olhos são bem ajustados à escuridão.",

  // Exploração
  "Acrobata": "Você tem um senso quase sobrenatural de equilíbrio.",
  "Batedor": "Você sabe como viajar rapidamente, de forma eficiente e invisível.",
  "Bem-Viajado": "Você conhece bem uma região e sabe o caminho para assentamentos e locais de interesse.",
  "Catador": "Você é habilidoso em obter recursos úteis de lugares onde outros não encontrariam nada.",
  "Detetive": "Você é habilidoso em rastrear pessoas em áreas urbanas.",
  "Escalador Hábil": "Você consegue escalar superfícies quase impossíveis.",
  "Escoteiro": "Você sabe como viajar rapidamente, de forma eficiente e invisível.",
  "Espeleólogo": "Você é habilidoso em navegação subterrânea, sobrevivência e travessia.",
  "Explorador": "Você sabe como explorar e se orientar em áreas desconhecidas com eficiência.",
  "Maestria em Armadilhas": "Você é habilidoso em montar e desativar armadilhas.",
  "Maestria em Montaria": "Você consegue manter qualquer montaria calma e sob controle.",
  "Pernas do Mar": "Você pode manejar e reparar pequenas embarcações sozinho.",
  "Especialista em Sobrevivência": "Você sabe como viver da terra.",
  "Despistador": "Você é habilidoso em cobrir seus rastros.",
  "Rastreador": "Você sabe como rastrear praticamente qualquer presa pelas terras selvagens.",

  // Conhecimento
  "Artesão": "Você é habilidoso em criar e reparar objetos com suas mãos.",
  "Avaliador": "Você é habilidoso em calcular o valor geral de tesouros encontrados.",
  "Bibliotecário": "Você é habilidoso em obter informações de bibliotecas.",
  "Burocrata": "Você conhece as leis locais e sabe como manipulá-las a seu favor.",
  "Cozinheiro": "Você é habilidoso em cozinhar e preparar alimentos.",
  "Curandeiro": "Você é habilidoso em meios não mágicos de cura e possui conhecimento sobre medicina e anatomia.",
  "Erudito": "Você teve uma educação ampla em um tema de sua escolha (história, política, biologia, filosofia etc.).",
  "Guardião do Saber": "Se você não souber algo, sabe por onde começar a procurar.",
  "Guardião da Tradição": "Se você não souber algo, sabe por onde começar a procurar.",
  "Herbologista": "Você sabe quais plantas e ervas podem curar ou produzir efeitos interessantes.",
  "Herborista": "Você sabe quais plantas e ervas podem curar ou produzir efeitos interessantes.",
  "Lenhador": "Você derruba objetos de madeira com golpes extremamente eficientes.",

  // Socialização
  "Acesso ao Mercado": "Você sabe como acessar toda a gama de comércio de um local — legal ou não.",
  "Amigos Influentes": "Você sabe como acessar a alta sociedade.",
  "Contatos no Submundo": "Você sabe como acessar as camadas mais baixas da sociedade.",
  "Conversador": "Você é habilidoso em manter conversas produtivas e obter informações de outras pessoas.",
  "Festeiro": "Você conhece bem as tabernas e sabe como obter informações ou fazer contatos.",
  "Negociador": "Você compra itens com 10% de desconto e vende itens com 10% a mais.",
  "Socialite": "Você pode se convidar para a maioria das festas, cerimônias ou eventos similares.",

  // Truques & Subterfúgio
  "Artista de Escapada": "Você consegue se desvencilhar de qualquer restrição, mesmo quando parece impossível.",
  "Artista de Fuga": "Você consegue se desvencilhar de qualquer restrição, mesmo quando parece impossível.",
  "Bolsos Ocultos": "Você é habilidoso em esconder pequenos itens em seu corpo e quase sempre pode produzir uma adaga quando necessário.",
  "Carteirista": "Você sabe como cortar uma bolsa.",
  "Trombadinha": "Você sabe como cortar uma bolsa.",
  "Falsificador": "Com os materiais certos e uma referência, você pode criar cópias perfeitas de documentos legais.",
  "Maestria em Disfarces": "Você sabe como adquirir, aplicar e utilizar um disfarce.",
  "Maestria em Fechaduras": "Você é habilidoso em abrir fechaduras.",
  "Maestria em Venenos": "Você sabe como identificar, tratar, fazer e administrar venenos perigosos.",
  "Oportunista": "Durante grandes distrações caóticas, os ataques contra você ficam Impedidos.",
  "Resistência a Veneno": "A mera exposição fez com que você fosse resistente ao veneno.",
  "Sutil": "Você não chama atenção quando não quer. Inimigos tendem a te ignorar ou dar-te baixa prioridade.",
  "Troco de Bolso": "Após um dia vagando pela cidade, faça um Teste de VON: sucesso = 1d10 moedas, falha = 1d4 moedas.",
  "Vigilância": "A cada semana investigando uma pessoa, instituição ou estrutura poderosa, você aprende um segredo sobre ela.",
};

// ── Careers ──────────────────────────────────────────────────
// isMagic: grants Magic Dice (Dotado skill)
// isFaith: grants Faith Dice (Devoção skill)
const CAREERS = [
  {
    id: "assassino",
    name: "Assassino",
    isMagic: false, isFaith: false,
    description: "Espiões e assassinos que fazem da morte e do roubo discretos um modo de vida.",
    skills: [
      "Proficiência com Armas Perfurantes",
      "Saque Rápido",
      "Golpes Selvagens",
      "Visão de Túnel",
      "Artista de Fuga",
      "Maestria em Disfarces",
      "Resistência a Veneno",
      "Maestria em Venenos",
      "Bolsos Ocultos",
      "Vigilância",
    ],
    souvenirs: [
      "Moeda manchada de sangue",
      "Frasco com líquido esverdeado",
      "Pedaço de papel com um nome parcial",
      "Mecha de cabelo perfumado",
    ],
  },
  {
    id: "ferreiro",
    name: "Ferreiro",
    isMagic: false, isFaith: false,
    description: "Habilidosos em derreter, dobrar e moldar metais — fabricam armas, armaduras e fazem reparos.",
    skills: [
      "Especialista em Armaduras",
      "Proficiência com Armas Contundentes",
      "Empunhadura Firme",
      "Proteger",
      "Golpes Selvagens",
      "Artesão",
      "Lenhador",
      "Acesso ao Mercado",
    ],
    souvenirs: [
      "Pequeno pingente de ferradura de ferro",
      "Pedaço de madeira queimada",
      "Prego enferrujado com design intricado",
      "Fragmento de bigorna enegrecido",
    ],
  },
  {
    id: "desamparado",
    name: "Desamparado",
    isMagic: false, isFaith: false,
    description: "Mendigos, vagabundos ou andarilhos que vagam sem rumo — ninguém conhece as ruas como eles.",
    skills: [
      "Alerta",
      "Defesa Ágil",
      "Contatos no Submundo",
      "Negociador",
      "Maestria em Fechaduras",
      "Maestria em Disfarces",
      "Trombadinha",
      "Troco de Bolso",
      "Bolsos Ocultos",
      "Sutil",
      "Vigilância",
      "Catador",
      "Detetive",
    ],
    souvenirs: [
      "Luva esfarrapada e sem dedos",
      "Tigela de mendigo quebrada de madeira",
      "Pedaço de cobertor gasto com remendos",
      "Moeda com um buraco no meio, usada como colar",
    ],
  },
  {
    id: "fazendeiro",
    name: "Fazendeiro",
    isMagic: false, isFaith: false,
    description: "Pessoas simples com resistência e conhecimento da terra — plantas, animais, artesanato e culinária.",
    skills: [
      "Afinidade com Animais",
      "Companheiro Animal",
      "Cozinheiro",
      "Artesão",
      "Herbologista",
      "Lenhador",
      "Maestria em Montaria",
      "Especialista em Sobrevivência",
      "Resistência a Veneno",
    ],
    souvenirs: [
      "Palha de trigo seca amarrada com fita vermelha",
      "Pequena vaca de madeira esculpida",
      "Punhado de sementes secas em um saquinho",
      "Pedaço desgastado do chapéu de um espantalho",
    ],
  },
  {
    id: "gladiador",
    name: "Gladiador",
    isMagic: false, isFaith: false,
    description: "Especialistas em combate individual, motivados pela glória — ou contratados para resolver disputas de forma violenta.",
    skills: [
      "Sede de Sangue",
      "Golpes Brutais",
      "Postura Defensiva",
      "Difícil de Matar",
      "Implacável",
      "Proficiência com Armas Perfurantes",
      "Lutador de Arena",
      "Proficiência com Armas Cortantes",
      "Visão de Túnel",
      "Habilidades Impressionantes",
      "Provocador",
      "Amigos Influentes",
    ],
    souvenirs: [
      "Pequeno pedaço quebrado de um antigo capacete",
      "Frasco de areia de uma arena",
      "Pedaço rasgado da capa de um rival",
      "Desenho rudimentar de um leão",
    ],
  },
  {
    id: "cacador",
    name: "Caçador",
    isMagic: false, isFaith: false,
    description: "Mestre em rastrear presas — usa furtividade, armadilhas e arco para abater alvos nas terras selvagens.",
    skills: [
      "Afinidade com Animais",
      "Disparo Incapacitante",
      "Proficiência com Armas Perfurantes",
      "Cozinheiro",
      "Herbologista",
      "Lenhador",
      "Maestria em Montaria",
      "Explorador",
      "Escalador Hábil",
      "Especialista em Sobrevivência",
      "Despistador",
      "Rastreador",
      "Maestria em Armadilhas",
      "Resistência a Veneno",
      "Maestria em Venenos",
    ],
    souvenirs: [
      "Garra de uma fera selvagem",
      "Feixe de tendões de animal",
      "Ponta de flecha de sílex lascada",
      "Tufo de pele de uma criatura lendária",
    ],
  },
  {
    id: "usuario-de-magia",
    name: "Usuário de Magia",
    isMagic: true, isFaith: false,
    description: "Estudiosos do arcano, fizeram um pacto terrível ou têm algo especial no sangue — capazes de lançar feitiçaria.",
    skills: [
      "Companheiro",
      "Elemental",
      "Dotado",
      "Sentidos Aguçados",
      "Sentido Mágico",
      "Visão Noturna",
      "Terceiro Olho",
      "Guardião do Saber",
    ],
    souvenirs: [
      "Fragmento de uma bola de cristal quebrada",
      "Página de um antigo livro de feitiçaria",
      "Asa de morcego seca",
      "Pequeno frasco de líquido luminoso",
    ],
  },
  {
    id: "mercenario",
    name: "Mercenário",
    isMagic: false, isFaith: false,
    description: "Guerreiros que trabalham por quem pagar — motivados por ganho pessoal, habilidosos em violência e intimidação.",
    skills: [
      "Alerta",
      "Sede de Sangue",
      "Proficiência com Armas Contundentes",
      "Pugilista",
      "Golpes Brutais",
      "Difícil de Matar",
      "Implacável",
      "Trespassar",
      "Proficiência com Armas Perfurantes",
      "Golpes Selvagens",
      "Proficiência com Armas Cortantes",
      "Comandante",
    ],
    souvenirs: [
      "Pedaço amassado de armadura",
      "Placa de cachorro de um camarada caído",
      "Contrato manchado de sangue",
      "Moeda estrangeira com marcas estranhas",
    ],
  },
  {
    id: "comerciante",
    name: "Comerciante",
    isMagic: false, isFaith: false,
    description: "Aventureiros viajados que buscam produtos exóticos — especialistas em comércio, persuasão e rotas de abastecimento.",
    skills: [
      "Companheiro",
      "Mediador",
      "Avaliador",
      "Burocrata",
      "Festeiro",
      "Amigos Influentes",
      "Negociador",
      "Acesso ao Mercado",
      "Conversador",
      "Socialite",
      "Explorador",
      "Detetive",
    ],
    souvenirs: [
      "Pequena balança para pesar mercadorias",
      "Moeda estrangeira",
      "Pedaço de tecido exótico",
      "Selo quebrado de uma carta importante",
    ],
  },
  {
    id: "menestrel",
    name: "Menestrel",
    isMagic: false, isFaith: false,
    description: "Vagantes do mundo que compartilham canções, histórias e músicas — suas palavras animam tabernas e inspiram feitos.",
    skills: [
      "Habilidades Impressionantes",
      "Inspirador",
      "Mediador",
      "Provocador",
      "Palavras Estimulantes",
      "Cantor",
      "Postura Defensiva",
      "Festeiro",
      "Conversador",
      "Socialite",
      "Maestria em Disfarces",
      "Oportunista",
      "Troco de Bolso",
      "Detetive",
    ],
    souvenirs: [
      "Corda quebrada de alaúde",
      "Pena de chapéu de bobo",
      "Fragmento da letra de uma canção famosa",
      "Sapatilha de dança desgastada",
    ],
  },
  {
    id: "nobre",
    name: "Nobre",
    isMagic: false, isFaith: false,
    description: "Pela violência, nascimento ou status social — ocupou uma posição de poder sobre os plebeus.",
    skills: [
      "Comandante",
      "Companheiro",
      "Habilidades Impressionantes",
      "Inspirador",
      "Provocador",
      "Postura Defensiva",
      "Guerreiro Montado",
      "Burocrata",
      "Erudito",
      "Festeiro",
      "Amigos Influentes",
      "Conversador",
      "Socialite",
    ],
    souvenirs: [
      "Anel de sinete com uma gema faltando",
      "Pequeno retrato de um ente querido",
      "Pedaço de uma antiga bandeira de família",
      "Botão dourado enferrujado",
    ],
  },
  {
    id: "sacerdote",
    name: "Sacerdote",
    isMagic: false, isFaith: true,
    description: "Dedicados a algo superior — um deus, um demônio, um conceito ou a própria natureza.",
    skills: [
      "Mediador",
      "Proficiência com Armas Contundentes",
      "Golpes Certos",
      "Devoção",
      "Cura Pelas Mãos",
      "Nariz Sensível",
      "Terceiro Olho",
      "Palavras de Graça",
      "Curandeiro",
      "Erudito",
      "Bibliotecário",
      "Guardião da Tradição",
    ],
    souvenirs: [
      "Conta de oração gasta",
      "Pequeno frasco de água benta",
      "Fragmento de um texto sagrado",
      "Pedaço de uma relíquia",
    ],
  },
  {
    id: "marinheiro",
    name: "Marinheiro",
    isMagic: false, isFaith: false,
    description: "Chamou os rios, lagos e mares de lar — acostumado ao tédio, trabalho árduo e perigo súbito da vida a bordo.",
    skills: [
      "Cantor",
      "Pugilista",
      "Defesa Ágil",
      "Acrobata",
      "Pernas do Mar",
      "Escalador Hábil",
      "Contatos no Submundo",
      "Oportunista",
    ],
    souvenirs: [
      "Bússola desgastada",
      "Pedaço de madeira flutuante em forma de barco",
      "Canto de um mapa desgastado",
      "Colar de conchas do mar",
    ],
  },
  {
    id: "escritor",
    name: "Escrivão",
    isMagic: false, isFaith: false,
    description: "Pesquisadores e professores bem educados — cartógrafos, historiadores, arqueólogos, filósofos e linguistas.",
    skills: [
      "Terceiro Olho",
      "Burocrata",
      "Erudito",
      "Bibliotecário",
      "Guardião da Tradição",
      "Falsificador",
    ],
    souvenirs: [
      "Pena com a ponta quebrada",
      "Tininha de tinta meio usada",
      "Pedaço de pergaminho com um símbolo misterioso",
      "Carimbo de selo de cera",
    ],
  },
  {
    id: "soldado",
    name: "Soldado",
    isMagic: false, isFaith: false,
    description: "Movido por dever — ao rei, senhor, vila ou ordem. Não pela glória nem pelo ouro.",
    skills: [
      "Comandante",
      "Inspirador",
      "Cantor",
      "Especialista em Armaduras",
      "Empunhadura Firme",
      "Difícil de Matar",
      "Guerreiro Montado",
      "Proficiência com Armas Perfurantes",
      "Proteger",
      "Proficiência com Armas Cortantes",
      "Soldado",
      "Maestria em Montaria",
      "Curandeiro",
    ],
    souvenirs: [
      "Medalha com uma inscrição desbotada",
      "Flecha quebrada",
      "Pedaço de uma bandeira de batalha desgastada",
      "Última vontade e testamento",
    ],
  },
  {
    id: "ladrao",
    name: "Ladrão",
    isMagic: false, isFaith: false,
    description: "Bolsista, charlatão, vigarista, bandido ou fraudador — manteve-se do outro lado da lei.",
    skills: [
      "Alerta",
      "Visão Noturna",
      "Acrobata",
      "Escalador Hábil",
      "Despistador",
      "Maestria em Armadilhas",
      "Contatos no Submundo",
      "Negociador",
      "Acesso ao Mercado",
      "Artista de Escapada",
      "Maestria em Fechaduras",
      "Oportunista",
      "Trombadinha",
      "Bolsos Ocultos",
      "Sutil",
      "Vigilância",
    ],
    souvenirs: [
      "Chave de fenda com uma ponta torcida",
      "Pequeno saco de moedas falsificadas",
      "Máscara preta com um rasgo",
      "Anel roubado com um brasão desconhecido",
    ],
  },
  {
    id: "viajante",
    name: "Viajante",
    isMagic: false, isFaith: false,
    description: "Testemunhou migrações maiores que florestas, sobreviveu a climas extremos — em casa no grande espaço aberto.",
    skills: [
      "Afinidade com Animais",
      "Companheiro Animal",
      "Cantor",
      "Defesa Ágil",
      "Rápido",
      "Sentidos Aguçados",
      "Sentido Mágico",
      "Nariz Sensível",
      "Escoteiro",
      "Espeleólogo",
      "Especialista em Sobrevivência",
      "Despistador",
      "Rastreador",
      "Bem-Viajado",
      "Cozinheiro",
      "Herborista",
      "Artista de Escapada",
      "Resistência a Veneno",
      "Maestria em Venenos",
      "Sutil",
    ],
    souvenirs: [
      "Bússola desgastada",
      "Pedaço de madeira em forma de barco",
      "Canto de um mapa desgastado",
      "Colar de conchas do mar",
    ],
  },
];

// ── Weapons ───────────────────────────────────────────────────
// type: "perfurante" | "contundente" | "cortante"
// speed: "Rápida" | "Equilibrada" | "Lenta"
// slots: inventory slots (Lenta/Volumosa = 2)
// specialEffect: true if the weapon has Sangramento/Brutal/Choque
//   (these are the options for Preferred Weapon)
const WEAPONS = [
  // ── Perfurantes ──
  { name: "Adaga",              type: "perfurante", dice: "d6",  speed: "Rápida",      slots: 1, properties: [],                  specialEffect: false },
  { name: "Adaga Cerimonial",   type: "perfurante", dice: "d6",  speed: "Rápida",      slots: 1, properties: ["Sangramento (5)"],  specialEffect: true,  effectName: "Sangramento (5)" },
  { name: "Adaga de Aparo",     type: "perfurante", dice: "d6",  speed: "Rápida",      slots: 1, properties: ["Contra-ataque (1)"], specialEffect: false },
  { name: "Rapieira",           type: "perfurante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Contra-ataque (2)"], specialEffect: false },
  { name: "Lança",              type: "perfurante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Alcance", "Empurrão (6)"], specialEffect: false },
  { name: "Picareta de Guerra", type: "perfurante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Sangramento (7)"],  specialEffect: true,  effectName: "Sangramento (7)" },
  { name: "Forquilha",          type: "perfurante", dice: "d10", speed: "Lenta",       slots: 2, properties: ["Volumosa"],         specialEffect: false },
  { name: "Lança de Caça",      type: "perfurante", dice: "d10", speed: "Lenta",       slots: 2, properties: ["Volumosa", "Alcance", "Empurrão (7)"], specialEffect: false },

  // ── Contundentes ──
  { name: "Porrete",            type: "contundente", dice: "d6",  speed: "Rápida",      slots: 1, properties: [],                   specialEffect: false },
  { name: "Cajado Simples",     type: "contundente", dice: "d6",  speed: "Rápida",      slots: 1, properties: ["Alcance"],           specialEffect: false },
  { name: "Cajado de Ermitão",  type: "contundente", dice: "d6",  speed: "Rápida",      slots: 1, properties: ["Alcance", "Choque (6)"], specialEffect: true, effectName: "Choque (6)" },
  { name: "Mangual",            type: "contundente", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Pesado (1)"],        specialEffect: false },
  { name: "Maça",               type: "contundente", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Choque (8)"],        specialEffect: true,  effectName: "Choque (8)" },
  { name: "Maça Espinhada",     type: "contundente", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Choque (7)"],        specialEffect: true,  effectName: "Choque (7)" },
  { name: "Malho",              type: "contundente", dice: "d10", speed: "Lenta",       slots: 2, properties: ["Volumosa", "Choque (6)"], specialEffect: true, effectName: "Choque (6)" },
  { name: "Martelo de Guerra",  type: "contundente", dice: "d10", speed: "Lenta",       slots: 2, properties: ["Volumosa", "Choque (7)"], specialEffect: true, effectName: "Choque (7)" },

  // ── Cortantes ──
  { name: "Espada Curta",         type: "cortante", dice: "d6",  speed: "Rápida",      slots: 1, properties: [],                   specialEffect: false },
  { name: "Machado",              type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Pesado (1)"],        specialEffect: false },
  { name: "Espada Longa",         type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Varredura (7)"],     specialEffect: false },
  { name: "Katana",               type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Rápida (2)"],        specialEffect: false },
  { name: "Cimitarra",            type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Varredura (6)"],     specialEffect: false },
  { name: "Machado do Carrasco",  type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Brutal (5)"],        specialEffect: true,  effectName: "Brutal (5)" },
  { name: "Flamberge",            type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 1, properties: ["Sangramento (6)"],   specialEffect: true,  effectName: "Sangramento (6)" },
  { name: "Alabarda",             type: "cortante", dice: "d8",  speed: "Equilibrada", slots: 2, properties: ["Volumosa", "Varredura (8)"], specialEffect: false },
  { name: "Machado de Duas Mãos", type: "cortante", dice: "d10", speed: "Lenta",       slots: 2, properties: ["Volumosa", "Pesado (2)"],    specialEffect: false },
  { name: "Espada de Duas Mãos",  type: "cortante", dice: "d10", speed: "Lenta",       slots: 2, properties: ["Volumosa"],          specialEffect: false },

  // ── Armas de Longa Distância (Ranged)
  { name: "Funda",            type: "",           dice: "d6",  speed: "Rápida", slots: 1, properties: ["Não pode atingir alvos distantes"], specialEffect: false },
  { name: "Arco Curto",       type: "perfurante", dice: "d6",  speed: "Rápida", slots: 2, properties: ["Volumosa"],                            specialEffect: false },
  { name: "Arco Longo",       type: "perfurante", dice: "d8",  speed: "Rápida", slots: 2, properties: ["Volumosa", "Pesado (1)"],             specialEffect: false },
  { name: "Balestra",         type: "perfurante", dice: "d8",  speed: "Rápida", slots: 2, properties: ["Volumosa", "Recarregar (1 turno)"], specialEffect: false },
  { name: "Grande Arco",      type: "perfurante", dice: "d10", speed: "Rápida", slots: 2, properties: ["Volumosa", "Pesado (1)", "Armar (1 turno)"], specialEffect: false },
];

// ── Starting Equipment Combos ─────────────────────────────────
const STARTING_COMBOS = [
  {
    id: "A",
    label: "Armadura Leve (1 Arm.) + 2 armas rápidas (d6)",
    armor: { name: "Armadura Leve", value: 1, slots: 1, bulky: false },
    weaponSpeed: "Rápida",
    weaponCount: 2,
  },
  {
    id: "B",
    label: "Escudo (1 Arm.) + 1 arma equilibrada (d8)",
    armor: { name: "Escudo", value: 1, slots: 1, bulky: false },
    weaponSpeed: "Equilibrada",
    weaponCount: 1,
  },
  {
    id: "C",
    label: "Armadura Média (2 Arm., Volumosa) + 1 arma lenta (d10)",
    armor: { name: "Armadura Média", value: 2, slots: 2, bulky: true },
    weaponSpeed: "Lenta",
    weaponCount: 1,
  },
];

// ── Fixed starting items (always granted) ─────────────────────
const FIXED_ITEMS = [
  { name: "3 dias de rações",  slots: 1 },
  { name: "Cantil (Dado de Uso d8)", slots: 1 },
  { name: "Tocha",             slots: 1 },
  { name: "Pederneira",        slots: 0 },
  { name: "Mochila",           slots: 0 },
];
