name: Sync Content from bdpbr Repo

on:
  push:
    branches:
      - master  # or the branch you want to sync from

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bdpbr Repo
        uses: actions/checkout@v2
        with:
          repository: Berger-DM/bdpbr
          ref: master  # or the branch you want to sync from

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone blockdodgeparry-br.github.io Repo
        run: |
          git clone https://github.com/blockdodgeparry-br/blockdodgeparry-br.github.io
          cd blockdodgeparry-br.github.io

      - name: Copy Files from bdpbr Repo to Pages Repo
        run: |
          # Assuming your content is in the root of bdpbr repo and should go into the root of blockdodgeparry-br.github.io
          cp -r ../bdpbr/* ./  # Copy everything from bdpbr into the Pages repo

      - name: Commit and Push Changes to blockdodgeparry-br.github.io
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S")  # Get the current date and time
          git add .
          git commit -m "Sync content from bdpbr repo on $DATE"  # Use $DATE in the commit message
          git push origin main
